const TEST_RECIPES = [
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 17,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 94,
    spoonacularScore: 98.0,
    healthScore: 75.0,
    creditsText: 'Pick Fresh Foods',
    license: 'CC BY 3.0',
    sourceName: 'Pick Fresh Foods',
    pricePerServing: 414.24,
    extendedIngredients: [
      {
        id: 98840,
        aisle: 'Produce',
        image: 'broccolini.jpg',
        consistency: 'solid',
        name: 'broccolini',
        nameClean: 'broccolini',
        original: '1 bunch broccolini, trimmed',
        originalString: '1 bunch broccolini, trimmed',
        originalName: 'broccolini, trimmed',
        amount: 1.0,
        unit: 'bunch',
        meta: ['trimmed'],
        metaInformation: ['trimmed'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'bunch',
            unitLong: 'bunch',
          },
          metric: {
            amount: 1.0,
            unitShort: 'bunch',
            unitLong: 'bunch',
          },
        },
      },
      {
        id: 11215,
        aisle: 'Produce',
        image: 'garlic.png',
        consistency: 'solid',
        name: 'garlic clove',
        nameClean: 'garlic',
        original: '1 garlic clove, minced',
        originalString: '1 garlic clove, minced',
        originalName: 'garlic clove, minced',
        amount: 1.0,
        unit: '',
        meta: ['minced'],
        metaInformation: ['minced'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 1.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 4053,
        aisle: 'Oil, Vinegar, Salad Dressing',
        image: 'olive-oil.jpg',
        consistency: 'liquid',
        name: 'olive oil',
        nameClean: 'olive oil',
        original: '1 tbsp olive oil',
        originalString: '1 tbsp olive oil',
        originalName: 'olive oil',
        amount: 1.0,
        unit: 'tbsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
          metric: {
            amount: 1.0,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
        },
      },
      {
        id: 11282,
        aisle: 'Produce',
        image: 'brown-onion.png',
        consistency: 'solid',
        name: 'onion',
        nameClean: 'onion',
        original: '½ cup onion',
        originalString: '½ cup onion',
        originalName: 'onion',
        amount: 0.5,
        unit: 'cup',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 118.294,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 20035,
        aisle: 'Pasta and Rice;Health Foods',
        image: 'uncooked-quinoa.png',
        consistency: 'solid',
        name: 'quinoa',
        nameClean: 'quinoa',
        original: '1 cup quinoa, rinsed',
        originalString: '1 cup quinoa, rinsed',
        originalName: 'quinoa, rinsed',
        amount: 1.0,
        unit: 'cup',
        meta: ['rinsed'],
        metaInformation: ['rinsed'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'cup',
            unitLong: 'cup',
          },
          metric: {
            amount: 236.588,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 6615,
        aisle: 'Canned and Jarred',
        image: 'chicken-broth.png',
        consistency: 'liquid',
        name: 'vegetable broth',
        nameClean: 'vegetable stock',
        original: '2 cups vegetable broth',
        originalString: '2 cups vegetable broth',
        originalName: 'vegetable broth',
        amount: 2.0,
        unit: 'cups',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 473.176,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 12155,
        aisle: 'Nuts;Baking',
        image: 'walnuts.jpg',
        consistency: 'solid',
        name: 'walnuts',
        nameClean: 'walnuts',
        original: '2 oz chopped walnuts',
        originalString: '2 oz chopped walnuts',
        originalName: 'chopped walnuts',
        amount: 2.0,
        unit: 'oz',
        meta: ['chopped'],
        metaInformation: ['chopped'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 56.699,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
    ],
    id: 715769,
    title: 'Broccolini Quinoa Pilaf',
    readyInMinutes: 30,
    servings: 2,
    sourceUrl: 'http://pickfreshfoods.com/broccolini-quinoa-pilaf/',
    image: 'https://spoonacular.com/recipeImages/715769-556x370.jpg',
    imageType: 'jpg',
    summary:
      'If you want to add more <b>Mediterranean</b> recipes to your recipe box, Broccolini Quinoa Pilaf might be a recipe you should try. One portion of this dish contains around <b>20g of protein</b>, <b>31g of fat</b>, and a total of <b>625 calories</b>. This recipe serves 2 and costs $4.14 per serving. A few people really liked this main course. 95 people have made this recipe and would make it again. Head to the store and pick up quinoa, garlic clove, olive oil, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>30 minutes</b>. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. It is brought to you by Pick Fresh Foods. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is awesome. Similar recipes include <a href="https://spoonacular.com/recipes/spring-broccolini-kale-quinoa-bowls-734866">Spring Broccolini & Kale Quinoa Bowls</a>, <a href="https://spoonacular.com/recipes/orange-sesame-salmon-with-quinoa-broccolini-839832">Orange-Sesame Salmon with Quinoa & Broccolini</a>, and <a href="https://spoonacular.com/recipes/black-pepper-goat-cheese-and-chard-quinoa-with-roasted-broccolini-625829">Black Pepper Goat Cheese and Chard Quinoa with Roasted Broccolini</a>.',
    cuisines: ['Mediterranean', 'Italian', 'European'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan'],
    occasions: [],
    winePairing: {},
    instructions:
      '<ol><li>In a large pan with lid heat olive oil over medium high heat. Add onions and cook for 1 minute. Add garlic and cook until onions are translucent and garlic is fragrant.</li><li>Add quinoa to pan, stir to combine. Slowly add in broth and bring to a boil.</li><li>Cover and reduce heat to low, cook for 15 minutes.</li><li>In the last 2-3 minutes of cooking add in broccolini on top of the quinoa (do not stir) and cover.</li><li>Uncover and toss broccolini and quinoa together.</li><li>Season to taste with salt and pepper.</li><li>Add walnuts and serve hot.</li></ol>',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'In a large pan with lid heat olive oil over medium high heat.',
            ingredients: [
              {
                id: 4053,
                name: 'olive oil',
                localizedName: 'olive oil',
                image: 'olive-oil.jpg',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
          },
          {
            number: 2,
            step: 'Add onions and cook for 1 minute.',
            ingredients: [
              {
                id: 11282,
                name: 'onion',
                localizedName: 'onion',
                image: 'brown-onion.png',
              },
            ],
            equipment: [],
            length: {
              number: 1,
              unit: 'minutes',
            },
          },
          {
            number: 3,
            step: 'Add garlic and cook until onions are translucent and garlic is fragrant.',
            ingredients: [
              {
                id: 11215,
                name: 'garlic',
                localizedName: 'garlic',
                image: 'garlic.png',
              },
              {
                id: 11282,
                name: 'onion',
                localizedName: 'onion',
                image: 'brown-onion.png',
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: 'Add quinoa to pan, stir to combine. Slowly add in broth and bring to a boil.Cover and reduce heat to low, cook for 15 minutes.In the last 2-3 minutes of cooking add in broccolini on top of the quinoa (do not stir) and cover.Uncover and toss broccolini and quinoa together.Season to taste with salt and pepper.',
            ingredients: [
              {
                id: 1102047,
                name: 'salt and pepper',
                localizedName: 'salt and pepper',
                image: 'salt-and-pepper.jpg',
              },
              {
                id: 98840,
                name: 'broccolini',
                localizedName: 'broccolini',
                image: 'broccolini.jpg',
              },
              {
                id: 20035,
                name: 'quinoa',
                localizedName: 'quinoa',
                image: 'uncooked-quinoa.png',
              },
              {
                id: 1006615,
                name: 'broth',
                localizedName: 'broth',
                image: 'chicken-broth.png',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
            length: {
              number: 18,
              unit: 'minutes',
            },
          },
          {
            number: 5,
            step: 'Add walnuts and serve hot.',
            ingredients: [
              {
                id: 12155,
                name: 'walnuts',
                localizedName: 'walnuts',
                image: 'walnuts.jpg',
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      'https://spoonacular.com/broccolini-quinoa-pilaf-715769',
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 11,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 11,
    spoonacularScore: 97.0,
    healthScore: 96.0,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 126.12,
    extendedIngredients: [
      {
        id: 11090,
        aisle: 'Produce',
        image: 'broccoli.jpg',
        consistency: 'solid',
        name: 'broccoli',
        nameClean: 'broccoli',
        original: '1 cup broccoli',
        originalString: '1 cup broccoli',
        originalName: 'broccoli',
        amount: 1.0,
        unit: 'cup',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'cup',
            unitLong: 'cup',
          },
          metric: {
            amount: 236.588,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 16058,
        aisle: 'Canned and Jarred',
        image: 'chickpeas.png',
        consistency: 'solid',
        name: 'canned chickpeas',
        nameClean: 'canned chickpeas',
        original: '1 can chickpeas, rinsed and drained',
        originalString: '1 can chickpeas, rinsed and drained',
        originalName: 'chickpeas, rinsed and drained',
        amount: 1.0,
        unit: 'can',
        meta: ['rinsed', 'drained'],
        metaInformation: ['rinsed', 'drained'],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'can',
            unitLong: 'can',
          },
          metric: {
            amount: 1.0,
            unitShort: 'can',
            unitLong: 'can',
          },
        },
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consistency: 'solid',
        name: 'carrots',
        nameClean: 'carrot',
        original: '2 large carrots, chopped',
        originalString: '2 large carrots, chopped',
        originalName: 'carrots, chopped',
        amount: 2.0,
        unit: 'large',
        meta: ['chopped'],
        metaInformation: ['chopped'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'large',
            unitLong: 'larges',
          },
          metric: {
            amount: 2.0,
            unitShort: 'large',
            unitLong: 'larges',
          },
        },
      },
      {
        id: 10111143,
        aisle: 'Produce',
        image: 'celery.jpg',
        consistency: 'solid',
        name: 'celery stalks',
        nameClean: 'celery sticks',
        original: '2 celery stalks, chopped ili 1/3 cup chopped celery root',
        originalString:
          '2 celery stalks, chopped ili 1/3 cup chopped celery root',
        originalName: 'celery stalks, chopped ili 1/3 cup chopped celery root',
        amount: 2.0,
        unit: '',
        meta: ['chopped'],
        metaInformation: ['chopped'],
        measures: {
          us: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
          metric: {
            amount: 2.0,
            unitShort: '',
            unitLong: '',
          },
        },
      },
      {
        id: 16070,
        aisle: 'Pasta and Rice;Canned and Jarred',
        image: 'lentils-brown.jpg',
        consistency: 'solid',
        name: 'cooked lentils',
        nameClean: 'cooked lentils',
        original: '½ cup cooked lentils',
        originalString: '½ cup cooked lentils',
        originalName: 'cooked lentils',
        amount: 0.5,
        unit: 'cup',
        meta: ['cooked'],
        metaInformation: ['cooked'],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 118.294,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 20028,
        aisle: 'Pasta and Rice;Ethnic Foods;Health Foods',
        image: 'couscous-cooked.jpg',
        consistency: 'solid',
        name: 'couscous',
        nameClean: 'couscous',
        original: '1 cup couscous',
        originalString: '1 cup couscous',
        originalName: 'couscous',
        amount: 1.0,
        unit: 'cup',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'cup',
            unitLong: 'cup',
          },
          metric: {
            amount: 236.588,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
      {
        id: 11165,
        aisle: 'Produce;Spices and Seasonings',
        image: 'cilantro.png',
        consistency: 'solid',
        name: 'fresh cilantro',
        nameClean: 'cilantro',
        original: 'Fresh cilantro, optional',
        originalString: 'Fresh cilantro, optional',
        originalName: 'Fresh cilantro, optional',
        amount: 3.0,
        unit: 'servings',
        meta: ['fresh'],
        metaInformation: ['fresh'],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 3.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 1012010,
        aisle: 'Spices and Seasonings',
        image: 'cinnamon.jpg',
        consistency: 'solid',
        name: 'ground cinnamon',
        nameClean: 'ground cinnamon',
        original: '⅛ tsp ground cinnamon',
        originalString: '⅛ tsp ground cinnamon',
        originalName: 'ground cinnamon',
        amount: 0.125,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.125,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.125,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 1002014,
        aisle: 'Spices and Seasonings',
        image: 'ground-cumin.jpg',
        consistency: 'solid',
        name: 'ground cumin',
        nameClean: 'cumin',
        original: '2 tsp ground cumin',
        originalString: '2 tsp ground cumin',
        originalName: 'ground cumin',
        amount: 2.0,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 2043,
        aisle: 'Spices and Seasonings',
        image: 'turmeric.jpg',
        consistency: 'solid',
        name: 'ground turmeric',
        nameClean: 'turmeric',
        original: '½ tsp ground turmeric',
        originalString: '½ tsp ground turmeric',
        originalName: 'ground turmeric',
        amount: 0.5,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 0.5,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 9152,
        aisle: 'Produce',
        image: 'lemon-juice.jpg',
        consistency: 'liquid',
        name: 'lemon juice',
        nameClean: 'lemon juice',
        original: '1 Tbs lemon juice',
        originalString: '1 Tbs lemon juice',
        originalName: 'lemon juice',
        amount: 1.0,
        unit: 'Tbs',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: 'Tbs',
            unitLong: 'Tb',
          },
          metric: {
            amount: 1.0,
            unitShort: 'Tbs',
            unitLong: 'Tb',
          },
        },
      },
      {
        id: 4053,
        aisle: 'Oil, Vinegar, Salad Dressing',
        image: 'olive-oil.jpg',
        consistency: 'liquid',
        name: 'olive oil',
        nameClean: 'olive oil',
        original: '2 tsp olive oil',
        originalString: '2 tsp olive oil',
        originalName: 'olive oil',
        amount: 2.0,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 2028,
        aisle: 'Spices and Seasonings',
        image: 'paprika.jpg',
        consistency: 'solid',
        name: 'paprika',
        nameClean: 'paprika',
        original: '2 tsp paprika',
        originalString: '2 tsp paprika',
        originalName: 'paprika',
        amount: 2.0,
        unit: 'tsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
          metric: {
            amount: 2.0,
            unitShort: 'tsps',
            unitLong: 'teaspoons',
          },
        },
      },
      {
        id: 1102047,
        aisle: 'Spices and Seasonings',
        image: 'salt-and-pepper.jpg',
        consistency: 'solid',
        name: 'salt and pepper',
        nameClean: 'salt and pepper',
        original: 'Salt and pepper',
        originalString: 'Salt and pepper',
        originalName: 'Salt and pepper',
        amount: 3.0,
        unit: 'servings',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 3.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
          metric: {
            amount: 3.0,
            unitShort: 'servings',
            unitLong: 'servings',
          },
        },
      },
      {
        id: 11887,
        aisle: 'Pasta and Rice',
        image: 'tomato-paste.jpg',
        consistency: 'solid',
        name: 'tomato paste',
        nameClean: 'tomato paste',
        original: '2-3 Tbs tomato paste',
        originalString: '2-3 Tbs tomato paste',
        originalName: 'tomato paste',
        amount: 2.0,
        unit: 'Tbs',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: 'Tbs',
            unitLong: 'Tbs',
          },
          metric: {
            amount: 2.0,
            unitShort: 'Tbs',
            unitLong: 'Tbs',
          },
        },
      },
      {
        id: 14412,
        aisle: 'Beverages',
        image: 'water.png',
        consistency: 'liquid',
        name: 'water',
        nameClean: 'water',
        original: '1 ½ cups water',
        originalString: '1 ½ cups water',
        originalName: 'water',
        amount: 1.5,
        unit: 'cups',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1.5,
            unitShort: 'cups',
            unitLong: 'cups',
          },
          metric: {
            amount: 354.882,
            unitShort: 'ml',
            unitLong: 'milliliters',
          },
        },
      },
    ],
    id: 652417,
    title: 'Moroccan chickpea and lentil stew',
    readyInMinutes: 30,
    servings: 3,
    sourceUrl:
      'http://www.foodista.com/recipe/C6DXLHJH/moroccan-chickpea-and-lentil-stew',
    image: 'https://spoonacular.com/recipeImages/652417-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Moroccan chickpean and lentil stew is a <b>dairy free, lacto ovo vegetarian, and vegan</b> main course. One portion of this dish contains around <b>20g of protein</b>, <b>7g of fat</b>, and a total of <b>467 calories</b>. This recipe serves 3. For <b>$1.34 per serving</b>, this recipe <b>covers 30%</b> of your daily requirements of vitamins and minerals. 11 person found this recipe to be tasty and satisfying. It will be a hit at your <b>Autumn</b> event. This recipe from Foodista requires lemon juice, ground turmeric, carrots, and ground cumin. From preparation to the plate, this recipe takes around <b>30 minutes</b>. With a spoonacular <b>score of 95%</b>, this dish is amazing. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/butternut-squash-chickpea-lentil-moroccan-stew-523871">Butternut Squash, Chickpea & Lentil Moroccan Stew</a>, <a href="https://spoonacular.com/recipes/crockpot-moroccan-lentil-and-chickpea-soup-840995">Crockpot Moroccan Lentil and Chickpea Soup</a>, and <a href="https://spoonacular.com/recipes/moroccan-chickpea-and-lentil-soup-harira-977492">Moroccan Chickpean and Lentil Soup (Harira)</a>.',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['dairy free', 'lacto ovo vegetarian', 'vegan'],
    occasions: ['fall', 'winter'],
    winePairing: {},
    instructions:
      '<ol><li>Heat oil in large saucepan over medium-high heat, add onion and cook for about 3 minutes.</li><li>Add celery, carrot and broccoli to pan and saut for about 5 minutes.</li><li>Add in all seasonings and cook additional 1 minute.</li><li>Add water, tomato paste, chickpeas and lentils, bring to a boil. Cover, reduce heat to low and simmer for 20 minutes.</li><li>Meanwhile, cook couscous in separate pan according to package directions.</li><li>Add cilantro and lemon juice to stew and serve over warm couscous.</li></ol>',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Heat oil in large saucepan over medium-high heat, add onion and cook for about 3 minutes.',
            ingredients: [
              {
                id: 11282,
                name: 'onion',
                localizedName: 'onion',
                image: 'brown-onion.png',
              },
              {
                id: 4582,
                name: 'cooking oil',
                localizedName: 'cooking oil',
                image: 'vegetable-oil.jpg',
              },
            ],
            equipment: [
              {
                id: 404669,
                name: 'sauce pan',
                localizedName: 'sauce pan',
                image: 'sauce-pan.jpg',
              },
            ],
            length: {
              number: 3,
              unit: 'minutes',
            },
          },
          {
            number: 2,
            step: 'Add celery, carrot and broccoli to pan and saut for about 5 minutes.',
            ingredients: [
              {
                id: 11090,
                name: 'broccoli',
                localizedName: 'broccoli',
                image: 'broccoli.jpg',
              },
              {
                id: 11124,
                name: 'carrot',
                localizedName: 'carrot',
                image: 'sliced-carrot.png',
              },
              {
                id: 11143,
                name: 'celery',
                localizedName: 'celery',
                image: 'celery.jpg',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
            length: {
              number: 5,
              unit: 'minutes',
            },
          },
          {
            number: 3,
            step: 'Add in all seasonings and cook additional 1 minute.',
            ingredients: [
              {
                id: 1042027,
                name: 'seasoning',
                localizedName: 'seasoning',
                image: 'seasoning.png',
              },
            ],
            equipment: [],
            length: {
              number: 1,
              unit: 'minutes',
            },
          },
          {
            number: 4,
            step: 'Add water, tomato paste, chickpeas and lentils, bring to a boil. Cover, reduce heat to low and simmer for 20 minutes.Meanwhile, cook couscous in separate pan according to package directions.',
            ingredients: [
              {
                id: 11887,
                name: 'tomato paste',
                localizedName: 'tomato paste',
                image: 'tomato-paste.jpg',
              },
              {
                id: 16057,
                name: 'chickpeas',
                localizedName: 'chickpeas',
                image: 'chickpeas.png',
              },
              {
                id: 20028,
                name: 'couscous',
                localizedName: 'couscous',
                image: 'couscous-cooked.jpg',
              },
              {
                id: 10316069,
                name: 'lentils',
                localizedName: 'lentils',
                image: 'lentils-brown.jpg',
              },
              {
                id: 14412,
                name: 'water',
                localizedName: 'water',
                image: 'water.png',
              },
            ],
            equipment: [
              {
                id: 404645,
                name: 'frying pan',
                localizedName: 'frying pan',
                image: 'pan.png',
              },
            ],
            length: {
              number: 20,
              unit: 'minutes',
            },
          },
          {
            number: 5,
            step: 'Add cilantro and lemon juice to stew and serve over warm couscous.',
            ingredients: [
              {
                id: 9152,
                name: 'lemon juice',
                localizedName: 'lemon juice',
                image: 'lemon-juice.jpg',
              },
              {
                id: 11165,
                name: 'cilantro',
                localizedName: 'cilantro',
                image: 'cilantro.png',
              },
              {
                id: 20028,
                name: 'couscous',
                localizedName: 'couscous',
                image: 'couscous-cooked.jpg',
              },
              {
                id: 0,
                name: 'stew',
                localizedName: 'stew',
                image: '',
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      'https://spoonacular.com/moroccan-chickpea-and-lentil-stew-652417',
  },
];
 

export default TEST_RECIPES;
